import Head from 'next/head';
import React from 'react';
import Header from '../components/Header';

function Blog() {
  return (
    <div id='blog__page'>
        <Head>
            <title>Hevelen Jeronymo | Blog </title>
            <meta name="description" content="Generated by create next app" />
        </Head>
        <Header />
        <main>

        </main>
    </div>
  )
}

export default Blog