import Head from 'next/head';
import React from 'react';
import Header from '../components/Header';
import Footer from '../components/Footer';

function Blog() {
  return (
    <div id='blog__page'>
        <Head>
            <title>Blog | Hevelen Jeronymo</title>
            <meta name="description" content="Generated by create next app" />
        </Head>
        <Header />
        <main>

        </main>
        <Footer />
    </div>
  )
}

export default Blog