import Head from 'next/head';
import BannerHero from '../components/BannerHero';
import Header from '../components/Header';
import SectionTwo from '../components/SectionTwo';
import Services from '../components/Services';

export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      
      <Header />
      <main>
        <BannerHero />
        <SectionTwo />
        <Services />
      </main>

      <footer>
      </footer>
    </div>
  )
}
